# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
