# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.URLField(default=b'https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-128.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
